version: '3'

services:
  client:
    build: ./client
    ports:
      - "4200:4200"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - CORS_ORIGIN=http://localhost:4200
    depends_on:
      - db

  db:
    build: ./database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: